"""Pydantic request and response schemas."""

from app.schemas.auth import (
    LoginRequest,
    LogoutResponse,
    RefreshRequest,
    SignupRequest,
    TokenResponse,
    UserResponse,
)
from app.schemas.chat import (
    ChatHistoryResponse,
    ChatRequest,
    ChatResponse,
    ChatSessionCreate,
    ChatSessionListResponse,
    ChatSessionResponse,
    Citation,
    MessageCreate,
    MessageResponse,
    StreamChunk,
)
from app.schemas.document import (
    ChunkingConfig,
    DocumentChunk,
    DocumentDeleteResponse,
    DocumentFormat,
    DocumentListResponse,
    DocumentMetadata,
    DocumentProcessingResult,
    DocumentResponse,
    DocumentStatus,
    DocumentUploadRequest,
    DocumentUploadResponse,
    EmbeddingConfig,
    ProcessingConfig,
)
from app.schemas.health import HealthResponse
from app.schemas.history import (
    HistoryDeleteResponse,
    HistoryFilterParams,
    HistoryFilterStatus,
    HistoryPaginationParams,
    HistoryRenameRequest,
    HistoryRenameResponse,
    HistoryRestoreResponse,
    HistorySearchRequest,
    HistorySearchResponse,
    HistorySessionListResponse,
    HistorySessionResponse,
    HistorySortField,
    HistorySortOrder,
    HistorySortParams,
)
from app.schemas.settings import (
    DEFAULT_SETTINGS,
    SettingsBase,
    SettingsCreate,
    SettingsResetResponse,
    SettingsResponse,
    SettingsUpdate,
)

__all__ = [
    "HealthResponse",
    "LoginRequest",
    "LogoutResponse",
    "RefreshRequest",
    "SignupRequest",
    "TokenResponse",
    "UserResponse",
    # Chat schemas
    "ChatRequest",
    "ChatResponse",
    "ChatSessionCreate",
    "ChatSessionResponse",
    "ChatSessionListResponse",
    "ChatHistoryResponse",
    "MessageCreate",
    "MessageResponse",
    "Citation",
    "StreamChunk",
    # Document schemas
    "DocumentFormat",
    "DocumentStatus",
    "DocumentUploadRequest",
    "DocumentUploadResponse",
    "DocumentChunk",
    "DocumentProcessingResult",
    "DocumentMetadata",
    "DocumentResponse",
    "DocumentListResponse",
    "DocumentDeleteResponse",
    "ChunkingConfig",
    "EmbeddingConfig",
    "ProcessingConfig",
    # History schemas
    "HistorySessionResponse",
    "HistorySessionListResponse",
    "HistorySearchRequest",
    "HistorySearchResponse",
    "HistoryRenameRequest",
    "HistoryRenameResponse",
    "HistoryDeleteResponse",
    "HistoryRestoreResponse",
    "HistoryPaginationParams",
    "HistorySortParams",
    "HistoryFilterParams",
    "HistorySortField",
    "HistorySortOrder",
    "HistoryFilterStatus",
    # Settings schemas
    "DEFAULT_SETTINGS",
    "SettingsBase",
    "SettingsCreate",
    "SettingsUpdate",
    "SettingsResponse",
    "SettingsResetResponse",
]
